### ISSUE TITLE
Update the list of interested people when toggling the "like" button

### ISSUE THREAD

**Issue by defaude** [jbob/the_queue#5]
Somewhat relates to #3 
Right now, the list of people interested in an item does not update when the AJAXified buttons are used.

**Comment by jbob** [comment]
Currently the server replies to Ajax requests for the like/thumbs button with:
```
{
  "message": "success"
}
```
It's easy to include the updated list, e.g. like this:
```
{
  "message": "success",
  "interested: [
    "foo",
    "bar",
    "baz"
  ]
}
```
Would you be willing to implement the client side changes?

**Comment by defaude** [comment]
Sure thäng!
